# Experimental!

# Arithmetic mean
Mean ← ÷⧻⟜/+
# Variance
Var ← -°√∩÷∩⊃⧻/+⟜°√
# Standard deviation
Stdev ← √Var

# μ₂   ←
# μ₁   ← ¬μ₂
# Pos  ←
# Time ←

# [μ₁.0] ⍉Pos
# ⍜°√/+-
# Prox ←

# ≡⊟Time Prox

≡⊟⊙(⍜°√/+-[¬⊙∩0]|⍉)

◌°▽
⊸≡⊣
≡/≠⧈₃⧈<
⊏+1⊚

×2⧈-⊸≡⊢

⊸⧅(÷Stdev:⌵-Mean,°˜⊂)
# ⍜⬚0↙₂∵⋅0
↧⊸↥0◿∞
⍣⊢∞⊚> 20 # Number of standard deviations at which to identify a destabilization

⊃(÷⧻⟜/+↙
| °⊟⍆⊕(÷⧻⟜/+)◿₂°⊏≡⊣𝄐↙
| ⬚∞⊏⊙⋅≡⊢)
